"""added model

Revision ID: 19dad58d92b2
Revises: 958ec597e787
Create Date: 2024-11-20 01:03:29.966111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dad58d92b2'
down_revision: Union[str, None] = '958ec597e787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('branch_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'pieces', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pieces', type_='foreignkey')
    op.drop_column('pieces', 'branch_id')
    # ### end Alembic commands ###
