"""null wallet address in User model

Revision ID: 63fb0db813b7
Revises: 84354e3b5661
Create Date: 2024-11-20 19:11:39.580392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fb0db813b7'
down_revision: Union[str, None] = '84354e3b5661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
