"""added null to nft branch

Revision ID: 73b80a9f90fa
Revises: 19dad58d92b2
Create Date: 2024-11-20 01:07:51.927901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b80a9f90fa'
down_revision: Union[str, None] = '19dad58d92b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pieces', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pieces', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
