"""added queue to nft piece

Revision ID: 84354e3b5661
Revises: 73b80a9f90fa
Create Date: 2024-11-20 01:22:59.497660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84354e3b5661'
down_revision: Union[str, None] = '73b80a9f90fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pieces', sa.Column('queue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pieces', 'queue')
    # ### end Alembic commands ###
