"""add users to branch modelh

Revision ID: 86bb5d7e4133
Revises: ed2c42406e0b
Create Date: 2024-11-19 23:05:16.006428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bb5d7e4133'
down_revision: Union[str, None] = 'ed2c42406e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
